  ### delete 
 DELETE/ http://localhost:3001/api/persons/4


### post
post http://localhost:3001/api/person
 Content-Type: application/json

 {
   "name" : "abdulmuijb",
   "number": "69956"
 }
  ### get

# GET http://localhost:3001/api/persons